version: '3.8'

services:
  app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html       
    ports:
      - "5173:5173" 
    depends_on:
      - mysql
      - redis
      - elasticsearch
    command: sh -c "./docker-entrypoint.sh"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - QUEUE_CONNECTION=redis
      - REDIS_CLIENT=phpredis  
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=elasticsearch:9200 
    working_dir: /var/www/html
    tty: true
    restart: unless-stopped
    networks:
      - laravel  
        
  queue:
    container_name: laravel-queue
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    command: sh -c "./queue-entrypoint.sh"
    working_dir: /var/www/html
    tty: true
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "8090:80"
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - laravel      

  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - laravel

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  
    networks:
      - laravel  
        
  npm:
    container_name: laravel-npm
    build:
      context: .
      dockerfile: Dockerfile    
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - laravel
    command: npm run dev

volumes:
  mysql_data:

networks:
  laravel:
